// نظام الترجمة - الإصدار العربي
export type Locale = 'ar' | 'en' | 'fr';

export const currentLocale: Locale = 'ar';

export const translations = {
  // عام
  app_name: 'BRAVO FORMULA & FACTORY',
  app_description: 'نظام متكامل لإدارة التركيبات والتصنيع',
  
  // القائمة الرئيسية
  nav: {
    dashboard: 'لوحة التحكم',
    raw_materials: 'المواد الخام',
    suppliers: 'الموردون',
    formulas: 'التركيبات',
    formula_lab: 'معمل التركيبات',
    products: 'المنتجات',
    production: 'التصنيع',
    inventory: 'المخزون',
    sales: 'المبيعات',
    invoices: 'الفواتير',
    customers: 'العملاء',
    debts: 'المديونيات',
    expenses: 'المصروفات',
    reports: 'التقارير',
    academy: 'الأكاديمية',
    books: 'الكتب الرقمية',
    settings: 'الإعدادات',
    users: 'المستخدمون',
    logout: 'تسجيل الخروج',
  },
  
  // الأزرار العامة
  buttons: {
    add: 'إضافة',
    edit: 'تعديل',
    delete: 'حذف',
    save: 'حفظ',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    close: 'إغلاق',
    search: 'بحث',
    filter: 'تصفية',
    export: 'تصدير',
    import: 'استيراد',
    print: 'طباعة',
    share: 'مشاركة',
    copy: 'نسخ',
    refresh: 'تحديث',
    back: 'رجوع',
    next: 'التالي',
    previous: 'السابق',
    view: 'عرض',
    details: 'التفاصيل',
    select: 'اختيار',
    select_all: 'اختيار الكل',
    deselect_all: 'إلغاء الاختيار',
    apply: 'تطبيق',
    reset: 'إعادة تعيين',
    calculate: 'حساب',
    create: 'إنشاء',
    duplicate: 'تكرار',
    archive: 'أرشفة',
    restore: 'استعادة',
  },
  
  // الرسائل
  messages: {
    success: 'تمت العملية بنجاح',
    error: 'حدث خطأ',
    warning: 'تحذير',
    info: 'معلومة',
    confirm_delete: 'هل أنت متأكد من الحذف؟',
    confirm_cancel: 'هل أنت متأكد من الإلغاء؟',
    no_data: 'لا توجد بيانات',
    loading: 'جاري التحميل...',
    saving: 'جاري الحفظ...',
    saved: 'تم الحفظ',
    deleted: 'تم الحذف',
    updated: 'تم التحديث',
    created: 'تم الإنشاء',
    required_field: 'هذا الحقل مطلوب',
    invalid_value: 'قيمة غير صالحة',
    connection_error: 'خطأ في الاتصال',
    offline: 'أنت غير متصل بالإنترنت',
    online: 'تم الاتصال بالإنترنت',
    sync_in_progress: 'جاري المزامنة...',
    sync_complete: 'تمت المزامنة',
  },
  
  // المواد الخام
  raw_materials: {
    title: 'المواد الخام',
    add_new: 'إضافة مادة خام',
    edit: 'تعديل المادة الخام',
    code: 'الكود',
    name: 'الاسم',
    scientific_name: 'الاسم العلمي',
    inci_name: 'اسم INCI',
    category: 'التصنيف',
    supplier: 'المورد',
    unit: 'الوحدة',
    function: 'الوظيفة',
    description: 'الوصف',
    usages: 'الاستخدامات',
    current_price: 'السعر الحالي',
    current_quantity: 'الكمية الحالية',
    reserved_quantity: 'الكمية المحجوزة',
    available_quantity: 'الكمية المتاحة',
    min_stock: 'الحد الأدنى',
    max_stock: 'الحد الأقصى',
    storage_conditions: 'ظروف التخزين',
    safety_instructions: 'تعليمات السلامة',
    warnings: 'التحذيرات',
    substitutes: 'البدائل',
    related_formulas: 'التركيبات المرتبطة',
    price_history: 'سجل الأسعار',
    low_stock: 'مخزون منخفض',
    out_of_stock: 'نفذ من المخزون',
  },
  
  // الموردون
  suppliers: {
    title: 'الموردون',
    add_new: 'إضافة مورد',
    edit: 'تعديل المورد',
    code: 'الكود',
    name: 'الاسم',
    contact_person: 'مسؤول التواصل',
    phone: 'الهاتف',
    email: 'البريد الإلكتروني',
    address: 'العنوان',
    balance: 'الرصيد',
    notes: 'ملاحظات',
  },
  
  // التركيبات
  formulas: {
    title: 'التركيبات',
    add_new: 'إضافة تركيبة',
    edit: 'تعديل التركيبة',
    code: 'الكود',
    name: 'الاسم',
    category: 'التصنيف',
    description: 'الوصف',
    base_batch_size: 'حجم الدفعة الأساسي',
    batch_unit: 'وحدة الدفعة',
    target_ph: 'درجة الحموضة المستهدفة',
    target_viscosity: 'اللزوجة المستهدفة',
    status: 'الحالة',
    version: 'الإصدار',
    ingredients: 'المكونات',
    steps: 'خطوات التصنيع',
    add_ingredient: 'إضافة مكون',
    add_step: 'إضافة خطوة',
    percentage: 'النسبة',
    quantity: 'الكمية',
    total_percentage: 'إجمالي النسب',
    total_cost: 'إجمالي التكلفة',
    material_cost: 'تكلفة المادة',
    notes: 'ملاحظات',
    safety_instructions: 'تعليمات السلامة',
    storage_instructions: 'تعليمات التخزين',
    packaging_instructions: 'تعليمات التعبئة',
    compare_versions: 'مقارنة الإصدارات',
    create_new_version: 'إنشاء إصدار جديد',
    status_draft: 'مسودة',
    status_testing: 'تحت الاختبار',
    status_approved: 'معتمدة',
    status_archived: 'مؤرشفة',
  },
  
  // معمل التركيبات
  formula_lab: {
    title: 'معمل التركيبات',
    calculate: 'حساب التركيبة',
    batch_size: 'حجم الدفعة',
    scale_recipe: 'تغيير حجم الدفعة',
    cost_breakdown: 'تفاصيل التكلفة',
    raw_materials_cost: 'تكلفة المواد الخام',
    packaging_cost: 'تكلفة التعبئة',
    labor_cost: 'تكلفة العمالة',
    electricity_cost: 'تكلفة الكهرباء',
    water_cost: 'تكلفة المياه',
    transport_cost: 'تكلفة النقل',
    overhead_cost: 'المصروفات العامة',
    other_costs: 'مصروفات أخرى',
    wastage: 'الفاقد',
    profit_margin: 'هامش الربح',
    selling_price: 'سعر البيع',
    save_formula: 'حفظ التركيبة',
    copy_formula: 'نسخ التركيبة',
    percentage_warning: 'تحذير: مجموع النسب',
    stock_warning: 'تحذير: مخزون غير كافٍ',
  },
  
  // المنتجات
  products: {
    title: 'المنتجات',
    add_new: 'إضافة منتج',
    edit: 'تعديل المنتج',
    code: 'الكود',
    sku: 'رمز المنتج',
    name: 'الاسم',
    category: 'التصنيف',
    formula: 'التركيبة',
    formula_version: 'إصدار التركيبة',
    description: 'الوصف',
    package_size: 'حجم العبوة',
    package_unit: 'وحدة العبوة',
    packaging: 'التعبئة',
    production_cost: 'تكلفة الإنتاج',
    wholesale_price: 'سعر الجملة',
    retail_price: 'سعر التجزئة',
    current_quantity: 'الكمية الحالية',
    min_stock: 'الحد الأدنى',
  },
  
  // التصنيع
  production: {
    title: 'التصنيع',
    batches: 'دفعات التصنيع',
    add_batch: 'إضافة دفعة تصنيع',
    batch_number: 'رقم الدفعة',
    product: 'المنتج',
    formula_version: 'إصدار التركيبة',
    planned_quantity: 'الكمية المخططة',
    actual_quantity: 'الكمية الفعلية',
    wastage: 'الفاقد',
    wastage_percentage: 'نسبة الفاقد',
    wastage_reason: 'سبب الفاقد',
    status: 'الحالة',
    planned_start: 'بداية مخططة',
    planned_end: 'نهاية مخططة',
    actual_start: 'بداية فعلية',
    actual_end: 'نهاية فعلية',
    total_cost: 'التكلفة الإجمالية',
    cost_per_unit: 'تكلفة الوحدة',
    check_stock: 'فحص المخزون',
    reserve_materials: 'حجز المواد',
    start_production: 'بدء التصنيع',
    complete_production: 'إنهاء التصنيع',
    quality_check: 'فحص الجودة',
    status_draft: 'مسودة',
    status_planned: 'مخطط',
    status_in_progress: 'جاري التصنيع',
    status_quality_check: 'فحص الجودة',
    status_completed: 'مكتمل',
    status_cancelled: 'ملغي',
    materials_required: 'المواد المطلوبة',
    materials_consumed: 'المواد المستهلكة',
  },
  
  // المخزون
  inventory: {
    title: 'المخزون',
    raw_materials: 'مخزون المواد الخام',
    products: 'مخزون المنتجات',
    packaging: 'مخزون التعبئة',
    movements: 'حركات المخزون',
    add_movement: 'إضافة حركة',
    item: 'الصنف',
    movement_type: 'نوع الحركة',
    quantity: 'الكمية',
    quantity_before: 'الكمية قبل',
    quantity_after: 'الكمية بعد',
    reference: 'المرجع',
    movement_purchase: 'شراء',
    movement_manual_add: 'إضافة يدوية',
    movement_production: 'استهلاك تصنيع',
    movement_sale: 'بيع',
    movement_return: 'مرتجع',
    movement_damaged: 'تالف',
    movement_expired: 'منتهي الصلاحية',
    movement_adjustment: 'تعديل',
    movement_transfer: 'نقل',
    low_stock_alert: 'تنبيه مخزون منخفض',
    expiring_soon: 'قرب انتهاء الصلاحية',
    inventory_value: 'قيمة المخزون',
  },
  
  // المبيعات
  sales: {
    title: 'المبيعات',
    new_sale: 'عملية بيع جديدة',
    customer: 'العميل',
    products: 'المنتجات',
    quantity: 'الكمية',
    unit_price: 'سعر الوحدة',
    discount: 'الخصم',
    tax: 'الضريبة',
    subtotal: 'المجموع الفرعي',
    total: 'الإجمالي',
    paid: 'المدفوع',
    remaining: 'المتبقي',
    payment_method: 'طريقة الدفع',
    confirm_sale: 'تأكيد البيع',
    today_sales: 'مبيعات اليوم',
    month_sales: 'مبيعات الشهر',
  },
  
  // الفواتير
  invoices: {
    title: 'الفواتير',
    add_new: 'إنشاء فاتورة',
    invoice_number: 'رقم الفاتورة',
    customer: 'العميل',
    date: 'التاريخ',
    due_date: 'تاريخ الاستحقاق',
    items: 'البنود',
    subtotal: 'المجموع الفرعي',
    discount: 'الخصم',
    tax: 'الضريبة',
    total: 'الإجمالي',
    paid: 'المدفوع',
    remaining: 'المتبقي',
    status: 'الحالة',
    status_draft: 'مسودة',
    status_confirmed: 'مؤكدة',
    status_paid: 'مدفوعة',
    status_partially_paid: 'مدفوعة جزئياً',
    status_cancelled: 'ملغية',
    print: 'طباعة الفاتورة',
    download_pdf: 'تحميل PDF',
    send: 'إرسال للعميل',
  },
  
  // العملاء
  customers: {
    title: 'العملاء',
    add_new: 'إضافة عميل',
    edit: 'تعديل العميل',
    code: 'الكود',
    name: 'الاسم',
    phone: 'الهاتف',
    email: 'البريد الإلكتروني',
    address: 'العنوان',
    credit_limit: 'الحد الائتماني',
    balance: 'الرصيد',
    total_purchases: 'إجمالي المشتريات',
    total_payments: 'إجمالي المدفوعات',
    account_statement: 'كشف الحساب',
    invoices: 'الفواتير',
    payments: 'المدفوعات',
  },
  
  // المديونيات
  debts: {
    title: 'المديونيات',
    customer: 'العميل',
    total_debt: 'إجمالي المديونية',
    overdue: 'متأخرة',
    due_soon: 'مستحقة قريباً',
    add_payment: 'إضافة دفعة',
    payment_history: 'سجل المدفوعات',
  },
  
  // المصروفات
  expenses: {
    title: 'المصروفات',
    add_new: 'إضافة مصروف',
    category: 'التصنيف',
    amount: 'المبلغ',
    date: 'التاريخ',
    description: 'الوصف',
    reference: 'المرجع',
    payment_method: 'طريقة الدفع',
    cat_electricity: 'كهرباء',
    cat_water: 'مياه',
    cat_labor: 'عمالة',
    cat_transport: 'نقل',
    cat_rent: 'إيجار',
    cat_maintenance: 'صيانة',
    cat_marketing: 'تسويق',
    cat_general: 'مصروفات عامة',
    cat_other: 'أخرى',
  },
  
  // التقارير
  reports: {
    title: 'التقارير',
    sales_report: 'تقرير المبيعات',
    profit_report: 'تقرير الأرباح',
    cost_report: 'تقرير التكاليف',
    inventory_report: 'تقرير المخزون',
    raw_materials_report: 'تقرير المواد الخام',
    production_report: 'تقرير التصنيع',
    wastage_report: 'تقرير الفاقد',
    customers_report: 'تقرير العملاء',
    debts_report: 'تقرير المديونيات',
    expenses_report: 'تقرير المصروفات',
    top_products: 'أكثر المنتجات مبيعاً',
    top_materials: 'أكثر المواد استخداماً',
    date_from: 'من تاريخ',
    date_to: 'إلى تاريخ',
    generate: 'إنشاء التقرير',
    export_excel: 'تصدير Excel',
    export_pdf: 'تصدير PDF',
  },
  
  // الأكاديمية
  academy: {
    title: 'الأكاديمية',
    lessons: 'الدروس',
    categories: 'التصنيفات',
    lesson: 'الدرس',
    introduction: 'المقدمة',
    materials: 'المواد',
    formula: 'التركيبة',
    steps: 'الخطوات',
    temperature: 'درجة الحرارة',
    mixing_time: 'زمن الخلط',
    ph: 'درجة الحموضة',
    common_mistakes: 'الأخطاء الشائعة',
    tips: 'النصائح',
    safety: 'السلامة',
    video: 'الفيديو',
    attachments: 'المرفقات',
    mark_complete: 'تحديد كمكتمل',
    save_lesson: 'حفظ الدرس',
  },
  
  // الكتب
  books: {
    title: 'الكتب الرقمية',
    book: 'كتاب',
    author: 'المؤلف',
    pages: 'الصفحات',
    free: 'مجاني',
    paid: 'مدفوع',
    download: 'تحميل',
    read: 'قراءة',
    downloads: 'التحميلات',
  },
  
  // طرق الدفع
  payment_methods: {
    cash: 'نقدي',
    bank_transfer: 'تحويل بنكي',
    vodafone_cash: 'فودافون كاش',
    instapay: 'إنستاباي',
    other: 'أخرى',
  },
  
  // الوحدات
  units: {
    mg: 'مليجرام',
    g: 'جرام',
    kg: 'كيلوجرام',
    ml: 'ملليلتر',
    l: 'لتر',
    piece: 'قطعة',
    percent: 'نسبة مئوية',
  },
  
  // التصنيفات
  categories: {
    detergents: 'المنظفات',
    cosmetics: 'مستحضرات التجميل',
    perfumes: 'العطور',
    soap: 'الصابون',
    hair_care: 'العناية بالشعر',
    skin_care: 'العناية بالبشرة',
    personal_care: 'العناية الشخصية',
    raw_materials: 'المواد الخام',
  },
  
  // لوحة التحكم
  dashboard: {
    title: 'لوحة التحكم',
    total_raw_materials: 'إجمالي المواد الخام',
    total_products: 'إجمالي المنتجات',
    total_formulas: 'إجمالي التركيبات',
    inventory_value: 'قيمة المخزون',
    today_sales: 'مبيعات اليوم',
    month_sales: 'مبيعات الشهر',
    total_debts: 'إجمالي المديونيات',
    low_stock_items: 'أصناف منخفضة المخزون',
    recent_production: 'آخر عمليات التصنيع',
    recent_invoices: 'آخر الفواتير',
    sales_chart: 'رسم بياني للمبيعات',
    top_products_chart: 'أكثر المنتجات مبيعاً',
    welcome: 'مرحباً بك في',
    quick_actions: 'إجراءات سريعة',
  },
  
  // الإعدادات
  settings: {
    title: 'الإعدادات',
    general: 'عام',
    organization: 'المؤسسة',
    users: 'المستخدمون',
    roles: 'الأدوار',
    permissions: 'الصلاحيات',
    categories: 'التصنيفات',
    units: 'الوحدات',
    backup: 'النسخ الاحتياطي',
    restore: 'الاستعادة',
    theme: 'المظهر',
    light_mode: 'الوضع الفاتح',
    language: 'اللغة',
    currency: 'العملة',
    tax_settings: 'إعدادات الضريبة',
    invoice_settings: 'إعدادات الفواتير',
    notification_settings: 'إعدادات الإشعارات',
  },
  
  // المستخدمون
  users: {
    title: 'المستخدمون',
    add_new: 'إضافة مستخدم',
    edit: 'تعديل المستخدم',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    role: 'الدور',
    permissions: 'الصلاحيات',
    active: 'نشط',
    inactive: 'غير نشط',
    last_login: 'آخر دخول',
    role_admin: 'مدير النظام',
    role_manager: 'مدير',
    role_production_manager: 'مدير إنتاج',
    role_accountant: 'محاسب',
    role_warehouse_manager: 'مسؤول مخزن',
    role_sales_manager: 'مسؤول مبيعات',
    role_user: 'مستخدم',
  },
} as const;

export type TranslationKey = keyof typeof translations;

export function t(key: string): string {
  const keys = key.split('.');
  let value: any = translations;
  for (const k of keys) {
    value = value?.[k];
  }
  return typeof value === 'string' ? value : key;
}

// دالة للحصول على الاسم باللغة الحالية
export function getLocalizedName(
  name: { ar: string; en?: string; fr?: string } | string | null | undefined
): string {
  if (!name) return '';
  if (typeof name === 'string') return name;
  return name[currentLocale] || name.ar || '';
}
